const $LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Industrial_Steam_Turbine', 'multiblock')
        .machine((holder) => new $LargeTurbineMachine(holder, GTValues.LV))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes("steam_turbine")
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE, (machine, recipe) => $LargeTurbineMachine.recipeModifier(machine, recipe)])
        .appearanceBlock(() => Block.getBlock('gtceu:solid_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
                .aisle("BGG", "GGG", "BGG")
                .aisle("GGG", "GDE", "GHG")
                .aisle("BGG", "GAG", "BGG")
                .aisle("BCC", "BFC", "BCC")
            .where("A", Predicates.blocks("gtceu:invar_frame"))
            .where("B", Predicates.any())
            .where('C', Predicates.blocks("gtceu:solid_machine_casing")
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setExactLimit(1)))
            .where("D", Predicates.blocks("gtceu:steel_pipe_casing"))
            .where("E", Predicates.ability(PartAbility.ROTOR_HOLDER).setExactLimit(1))
            .where("F", Predicates.controller(Predicates.blocks(definition.get())))
            .where("G", Predicates.blocks("gtceu:solid_machine_casing"))
            .where("H", Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))
            .build())
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/generator/large_steam_turbine")
});
